### ISSUE TITLE
安装完插件，后台直接崩溃了。

### ISSUE THREAD

**Issue by dexterlaw** [geekeren/WordPressShuoShuo#3]
Fatal error: Uncaught Error: Attempt to modify property "response" on bool in /www/wwwroot/www.ilvniao.com/wp-content/themes/Autumn-Pro/admin/updater/theme-updater-class.php:120 Stack trace: #0 /www/wwwroot/www.ilvniao.com/wp-includes/class-wp-hook.php(309): EDD_Theme_Updater->theme_update_transient() #1 /www/wwwroot/www.ilvniao.com/wp-includes/plugin.php(189): WP_Hook->apply_filters() #2 /www/wwwroot/www.ilvniao.com/wp-includes/option.php(1957): apply_filters() #3 /www/wwwroot/www.ilvniao.com/wp-includes/update.php(790): get_site_transient() #4 /www/wwwroot/www.ilvniao.com/wp-admin/menu.php(33): wp_get_update_data() #5 /www/wwwroot/www.ilvniao.com/wp-admin/admin.php(158): require('...') #6 /www/wwwroot/www.ilvniao.com/wp-admin/themes.php(10): require_once('...') #7 {main} thrown in /www/wwwroot/www.ilvniao.com/wp-content/themes/Autumn-Pro/admin/updater/theme-updater-class.php on line 120

这个是安装到我现在的主题里后，点击启用插件，就显示这样，然后也进不去后台了。。
要怎么搞，大佬。

**Comment by webbrain-dev** [comment]
大佬你好，已经开了 PR #4 修复这个问题：https://github.com/geekeren/WordPressShuoShuo/pull/4

原因是主题更新器在获取更新信息时，某些情况下返回的是 bool，而不是预期的对象，导致后续直接访问/修改 `response` 属性时报 Fatal error，进而影响后台访问。PR 里已经加了对返回值的判断和兜底处理，避免这种崩溃，麻烦你测试一下。
